version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: nkambwe/udacity-proxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: nkambwe/udacity-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: nkambwe/udacity-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: nkambwe/udacity-front:local
